# Jupyter Notebook Title

This Jupyter Notebook contains multiple cells with code and markdown content. It includes data manipulation using pandas, visualization using matplotlib, and documentation using markdown cells.

## Introduction

In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
df  = pd.read_csv('datasets\projects_data.csv')
df.head()

,id,regionname,countryname,prodline,lendinginstr,lendinginstrtype,envassesmentcategorycode,supplementprojectflg,productlinetype,projectstatusdisplay,status,project_name,boardapprovaldate,board_approval_month,closingdate,lendprojectcost,ibrdcommamt,idacommamt,totalamt,grantamt,borrower,impagency,url,projectdoc,majorsector_percent,sector1,sector2,sector3,sector4,sector5,sector,mjsector1,mjsector2,mjsector3,mjsector4,mjsector5,mjsector,theme1,theme2,theme3,theme4,theme5,theme,goal,financier,mjtheme1name,mjtheme2name,mjtheme3name,mjtheme4name,mjtheme5name,location,GeoLocID,GeoLocName,Latitude,Longitude,Country,Unnamed: 56
0,P162228,Other,World;World,RE,Investment Project Financing,IN,C,N,L,Active,Active,Creating a Trade in Value-Added Database for ...,2018-06-28T00:00:00Z,June,NaN,"500,000",0,0,0,"500,000",NaN,NaN,http://projects.worldbank.org/P162228?lang=en,NaN,NaN,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P163962,Africa,Democratic Republic of the Congo;Democratic Re...,PE,Investment Project Financing,IN,B,N,L,Active,Active,Productive Inclusion Project,2018-06-28T00:00:00Z,June,2023-12-31T00:00:00Z,"200,000,000",0,"200,000,000","200,000,000",0,NaN,NaN,http://projects.worldbank.org/P163962?lang=en,NaN,NaN,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,P167672,South Asia,People's Republic of Bangladesh;People's Repub...,PE,Investment Project Financing,IN,NaN,Y,L,Active,Active,Additional Financing for Health Sector Support...,2018-06-28T00:00:00Z,June,NaN,"50,000,000",0,"58,330,000","58,330,000",0,NaN,NaN,http://projects.worldbank.org/P167672?lang=en,NaN,NaN,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,P158768,South Asia,Islamic Republic of Afghanistan;Islamic Repu...,PE,Investment Project Financing,IN,A,N,L,Active,Active,Public-Private Partnerships and Public Investm...,2018-06-27T00:00:00Z,June,2023-06-28T00:00:00Z,"50,000,000",0,"20,000,000","20,000,000",0,IIST,IIST,http://projects.worldbank.org/P158768?lang=en,NaN,NaN,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,P161364,Africa,Federal Republic of Nigeria;Federal Republic o...,PE,Investment Project Financing,IN,B,N,L,Active,Active,Nigeria For Women Project,2018-06-27T00:00:00Z,June,2023-05-31T00:00:00Z,"100,000,000",0,"100,000,000","100,000,000",0,NaN,NaN,http://projects.worldbank.org/P161364?lang=en,NaN,NaN,Social Protection!$!63!$!SA,Other Industry; Trade and Services!$!25!$!YZ,Other Agriculture; Fishing and Forestry!$!2!$!AZ,Other Public Administration!$!10!$!BZ,NaN,Social Protection;Social Protection;Other Indu...,NaN,NaN,NaN,NaN,NaN,Social Protection;Social Protection;Industry; ...,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0002327546!$!Ogun State!$!7!$!3.58333!$!NG;000...,0002327546;0002328925;0002565340;0002565343;00...,Ogun State;Niger State;Abia State;Edo;Kebbi St...,7;10;5.41667;6.5;11.5;8,3.58333;6;7.5;6;4;10.5,NG;NG;NG;NG;NG;NG,NaN

## Data

In [33]:
#show the columns
df.shape

(18248, 57)

In [34]:
# #delete unnamed column
# df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
# df.columns

In [35]:
#use delimiter to split string ; in column countryname maxsplit=1
df['countryname'] = df['countryname'].str.split(';', n=1).str[0]
df.head()

,id,regionname,countryname,prodline,lendinginstr,lendinginstrtype,envassesmentcategorycode,supplementprojectflg,productlinetype,projectstatusdisplay,status,project_name,boardapprovaldate,board_approval_month,closingdate,lendprojectcost,ibrdcommamt,idacommamt,totalamt,grantamt,borrower,impagency,url,projectdoc,majorsector_percent,sector1,sector2,sector3,sector4,sector5,sector,mjsector1,mjsector2,mjsector3,mjsector4,mjsector5,mjsector,theme1,theme2,theme3,theme4,theme5,theme,goal,financier,mjtheme1name,mjtheme2name,mjtheme3name,mjtheme4name,mjtheme5name,location,GeoLocID,GeoLocName,Latitude,Longitude,Country,Unnamed: 56
0,P162228,Other,World,RE,Investment Project Financing,IN,C,N,L,Active,Active,Creating a Trade in Value-Added Database for ...,2018-06-28T00:00:00Z,June,NaN,"500,000",0,0,0,"500,000",NaN,NaN,http://projects.worldbank.org/P162228?lang=en,NaN,NaN,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P163962,Africa,Democratic Republic of the Congo,PE,Investment Project Financing,IN,B,N,L,Active,Active,Productive Inclusion Project,2018-06-28T00:00:00Z,June,2023-12-31T00:00:00Z,"200,000,000",0,"200,000,000","200,000,000",0,NaN,NaN,http://projects.worldbank.org/P163962?lang=en,NaN,NaN,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,P167672,South Asia,People's Republic of Bangladesh,PE,Investment Project Financing,IN,NaN,Y,L,Active,Active,Additional Financing for Health Sector Support...,2018-06-28T00:00:00Z,June,NaN,"50,000,000",0,"58,330,000","58,330,000",0,NaN,NaN,http://projects.worldbank.org/P167672?lang=en,NaN,NaN,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,P158768,South Asia,Islamic Republic of Afghanistan,PE,Investment Project Financing,IN,A,N,L,Active,Active,Public-Private Partnerships and Public Investm...,2018-06-27T00:00:00Z,June,2023-06-28T00:00:00Z,"50,000,000",0,"20,000,000","20,000,000",0,IIST,IIST,http://projects.worldbank.org/P158768?lang=en,NaN,NaN,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,P161364,Africa,Federal Republic of Nigeria,PE,Investment Project Financing,IN,B,N,L,Active,Active,Nigeria For Women Project,2018-06-27T00:00:00Z,June,2023-05-31T00:00:00Z,"100,000,000",0,"100,000,000","100,000,000",0,NaN,NaN,http://projects.worldbank.org/P161364?lang=en,NaN,NaN,Social Protection!$!63!$!SA,Other Industry; Trade and Services!$!25!$!YZ,Other Agriculture; Fishing and Forestry!$!2!$!AZ,Other Public Administration!$!10!$!BZ,NaN,Social Protection;Social Protection;Other Indu...,NaN,NaN,NaN,NaN,NaN,Social Protection;Social Protection;Industry; ...,!$!0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0002327546!$!Ogun State!$!7!$!3.58333!$!NG;000...,0002327546;0002328925;0002565340;0002565343;00...,Ogun State;Niger State;Abia State;Edo;Kebbi St...,7;10;5.41667;6.5;11.5;8,3.58333;6;7.5;6;4;10.5,NG;NG;NG;NG;NG;NG,NaN

In [36]:

# keep only id	regionname	countryname	prodline	lendinginstr	lendinginstrtype	envassesmentcategorycode	supplementprojectflg	productlinetype	projectstatusdisplay	status	project_name	boardapprovaldate	board_approval_month	closingdate	lendprojectcost	ibrdcommamt	idacommamt	totalamt	grantamt	borrower	impagency	url
df = df[['id', 'regionname', 'countryname', 'prodline', 'lendinginstr', 'lendinginstrtype', 'envassesmentcategorycode', 'supplementprojectflg', 'productlinetype', 'projectstatusdisplay', 'status', 'project_name', 'boardapprovaldate', 'board_approval_month', 'closingdate', 'lendprojectcost', 'ibrdcommamt', 'idacommamt', 'totalamt', 'grantamt', 'borrower', 'impagency', 'url']]
df.head()

,id,regionname,countryname,prodline,lendinginstr,lendinginstrtype,envassesmentcategorycode,supplementprojectflg,productlinetype,projectstatusdisplay,status,project_name,boardapprovaldate,board_approval_month,closingdate,lendprojectcost,ibrdcommamt,idacommamt,totalamt,grantamt,borrower,impagency,url
0,P162228,Other,World,RE,Investment Project Financing,IN,C,N,L,Active,Active,Creating a Trade in Value-Added Database for ...,2018-06-28T00:00:00Z,June,NaN,"500,000",0,0,0,"500,000",NaN,NaN,http://projects.worldbank.org/P162228?lang=en
1,P163962,Africa,Democratic Republic of the Congo,PE,Investment Project Financing,IN,B,N,L,Active,Active,Productive Inclusion Project,2018-06-28T00:00:00Z,June,2023-12-31T00:00:00Z,"200,000,000",0,"200,000,000","200,000,000",0,NaN,NaN,http://projects.worldbank.org/P163962?lang=en
2,P167672,South Asia,People's Republic of Bangladesh,PE,Investment Project Financing,IN,NaN,Y,L,Active,Active,Additional Financing for Health Sector Support...,2018-06-28T00:00:00Z,June,NaN,"50,000,000",0,"58,330,000","58,330,000",0,NaN,NaN,http://projects.worldbank.org/P167672?lang=en
3,P158768,South Asia,Islamic Republic of Afghanistan,PE,Investment Project Financing,IN,A,N,L,Active,Active,Public-Private Partnerships and Public Investm...,2018-06-27T00:00:00Z,June,2023-06-28T00:00:00Z,"50,000,000",0,"20,000,000","20,000,000",0,IIST,IIST,http://projects.worldbank.org/P158768?lang=en
4,P161364,Africa,Federal Republic of Nigeria,PE,Investment Project Financing,IN,B,N,L,Active,Active,Nigeria For Women Project,2018-06-27T00:00:00Z,June,2023-05-31T00:00:00Z,"100,000,000",0,"100,000,000","100,000,000",0,NaN,NaN,http://projects.worldbank.org/P161364?lang=en

In [37]:
#convert boardapprovaldate and closingdate to datetime
df['boardapprovaldate'] = pd.to_datetime(df['boardapprovaldate'])
df['closingdate'] = pd.to_datetime(df['closingdate'])
#check the data type
df.dtypes

id                                       object
regionname                               object
countryname                              object
prodline                                 object
lendinginstr                             object
lendinginstrtype                         object
envassesmentcategorycode                 object
supplementprojectflg                     object
productlinetype                          object
projectstatusdisplay                     object
status                                   object
project_name                             object
boardapprovaldate           datetime64[ns, UTC]
board_approval_month                     object
closingdate                 datetime64[ns, UTC]
lendprojectcost                          object
ibrdcommamt                              object
idacommamt                               object
totalamt                                 object
grantamt                                 object
borrower                                 object
impagency                                object
url                                      object
dtype: object

In [38]:
df['lendprojectcost'] = df['lendprojectcost'].str.replace(',', '').astype(float)
df['ibrdcommamt'] = df['ibrdcommamt'].str.replace(',', '').astype(float)
df['idacommamt'] = df['idacommamt'].str.replace(',', '').astype(float)
df['totalamt'] = df['totalamt'].str.replace(',', '').astype(float)
df['grantamt'] = df['grantamt'].str.replace(',', '').astype(float)

In [39]:
#check data type
df.dtypes

id                                       object
regionname                               object
countryname                              object
prodline                                 object
lendinginstr                             object
lendinginstrtype                         object
envassesmentcategorycode                 object
supplementprojectflg                     object
productlinetype                          object
projectstatusdisplay                     object
status                                   object
project_name                             object
boardapprovaldate           datetime64[ns, UTC]
board_approval_month                     object
closingdate                 datetime64[ns, UTC]
lendprojectcost                         float64
ibrdcommamt                             float64
idacommamt                              float64
totalamt                                float64
grantamt                                float64
borrower                                 object
impagency                                object
url                                      object
dtype: object

## resolve missing values

In [57]:
#check missing values
df.isnull().sum()

id                          0
regionname                  0
countryname                 0
prodline                    0
lendinginstr                0
lendinginstrtype            0
envassesmentcategorycode    0
supplementprojectflg        0
productlinetype             0
projectstatusdisplay        0
status                      0
project_name                0
boardapprovaldate           0
board_approval_month        0
closingdate                 0
lendprojectcost             0
ibrdcommamt                 0
idacommamt                  0
totalamt                    0
grantamt                    0
borrower                    0
impagency                   0
url                         0
dtype: int64

In [54]:
df.shape()

       lendprojectcost   ibrdcommamt    idacommamt      totalamt      grantamt
count         18191.00      18191.00      18191.00      18191.00      18191.00
mean      134725198.98   42218958.83   22505976.58   64724935.96    1882870.10
std      1131974041.60  119513569.26   58155234.92  127096500.07   42314197.85
min               0.00          0.00          0.00          0.00          0.00
25%         9185000.00          0.00          0.00    5000000.00          0.00
50%        30000000.00          0.00          0.00   23200000.00          0.00
75%       100000000.00   30000000.00   20000000.00   70330000.00          0.00
max     93007000000.00 3750000000.00 1200000000.00 3750000000.00 5330000000.00

In [45]:
df.head()

,id,regionname,countryname,prodline,lendinginstr,lendinginstrtype,envassesmentcategorycode,supplementprojectflg,productlinetype,projectstatusdisplay,status,project_name,boardapprovaldate,board_approval_month,closingdate,lendprojectcost,ibrdcommamt,idacommamt,totalamt,grantamt,borrower,impagency,url
0,P162228,Other,World,RE,Investment Project Financing,IN,C,N,L,Active,Active,Creating a Trade in Value-Added Database for ...,2018-06-28 00:00:00+00:00,June,NaT,500000.00,0.00,0.00,0.00,500000.00,EET,IIST,http://projects.worldbank.org/P162228?lang=en
1,P163962,Africa,Democratic Republic of the Congo,PE,Investment Project Financing,IN,B,N,L,Active,Active,Productive Inclusion Project,2018-06-28 00:00:00+00:00,June,2023-12-31 00:00:00+00:00,200000000.00,0.00,200000000.00,200000000.00,0.00,EET,IIST,http://projects.worldbank.org/P163962?lang=en
2,P167672,South Asia,People's Republic of Bangladesh,PE,Investment Project Financing,IN,B,Y,L,Active,Active,Additional Financing for Health Sector Support...,2018-06-28 00:00:00+00:00,June,NaT,50000000.00,0.00,58330000.00,58330000.00,0.00,EET,IIST,http://projects.worldbank.org/P167672?lang=en
3,P158768,South Asia,Islamic Republic of Afghanistan,PE,Investment Project Financing,IN,A,N,L,Active,Active,Public-Private Partnerships and Public Investm...,2018-06-27 00:00:00+00:00,June,2023-06-28 00:00:00+00:00,50000000.00,0.00,20000000.00,20000000.00,0.00,IIST,IIST,http://projects.worldbank.org/P158768?lang=en
4,P161364,Africa,Federal Republic of Nigeria,PE,Investment Project Financing,IN,B,N,L,Active,Active,Nigeria For Women Project,2018-06-27 00:00:00+00:00,June,2023-05-31 00:00:00+00:00,100000000.00,0.00,100000000.00,100000000.00,0.00,EET,IIST,http://projects.worldbank.org/P161364?lang=en

In [41]:
#remove missing valuies in supplementprojectflg, projectstatusdisplay, status
df = df.dropna(subset=['supplementprojectflg'])
df = df.dropna(subset=['projectstatusdisplay'])
df = df.dropna(subset=['status'])

,id,regionname,countryname,prodline,lendinginstr,lendinginstrtype,envassesmentcategorycode,supplementprojectflg,productlinetype,projectstatusdisplay,status,project_name,boardapprovaldate,board_approval_month,closingdate,lendprojectcost,ibrdcommamt,idacommamt,totalamt,grantamt,borrower,impagency,url
0,P162228,Other,World,RE,Investment Project Financing,IN,C,N,L,Active,Active,Creating a Trade in Value-Added Database for ...,2018-06-28 00:00:00+00:00,June,NaT,500000.00,0.00,0.00,0.00,500000.00,NaN,NaN,http://projects.worldbank.org/P162228?lang=en
1,P163962,Africa,Democratic Republic of the Congo,PE,Investment Project Financing,IN,B,N,L,Active,Active,Productive Inclusion Project,2018-06-28 00:00:00+00:00,June,2023-12-31 00:00:00+00:00,200000000.00,0.00,200000000.00,200000000.00,0.00,NaN,NaN,http://projects.worldbank.org/P163962?lang=en
2,P167672,South Asia,People's Republic of Bangladesh,PE,Investment Project Financing,IN,NaN,Y,L,Active,Active,Additional Financing for Health Sector Support...,2018-06-28 00:00:00+00:00,June,NaT,50000000.00,0.00,58330000.00,58330000.00,0.00,NaN,NaN,http://projects.worldbank.org/P167672?lang=en
3,P158768,South Asia,Islamic Republic of Afghanistan,PE,Investment Project Financing,IN,A,N,L,Active,Active,Public-Private Partnerships and Public Investm...,2018-06-27 00:00:00+00:00,June,2023-06-28 00:00:00+00:00,50000000.00,0.00,20000000.00,20000000.00,0.00,IIST,IIST,http://projects.worldbank.org/P158768?lang=en
4,P161364,Africa,Federal Republic of Nigeria,PE,Investment Project Financing,IN,B,N,L,Active,Active,Nigeria For Women Project,2018-06-27 00:00:00+00:00,June,2023-05-31 00:00:00+00:00,100000000.00,0.00,100000000.00,100000000.00,0.00,NaN,NaN,http://projects.worldbank.org/P161364?lang=en

In [42]:
#fill missing values with mode
df['lendinginstr'] = df['lendinginstr'].fillna(df['lendinginstr'].mode()[0])
df['lendinginstrtype'] = df['lendinginstrtype'].fillna(df['lendinginstrtype'].mode()[0])
df['envassesmentcategorycode'] = df['envassesmentcategorycode'].fillna(df['envassesmentcategorycode'].mode()[0])

In [43]:
#fix borrower, impagency column missing values with mode
df['borrower'] = df['borrower'].fillna(df['borrower'].mode()[0])
df['impagency'] = df['impagency'].fillna(df['impagency'].mode()[0])

In [51]:
#handle missing values in lendprojectcost, ibrdcommamt, idacommamt, totalamt, grantamt
df['lendprojectcost'] = df['lendprojectcost'].fillna(df['lendprojectcost'].mean())
df['ibrdcommamt'] = df['ibrdcommamt'].fillna(df['ibrdcommamt'].mean())
df['idacommamt'] = df['idacommamt'].fillna(df['idacommamt'].mean())
df['totalamt'] = df['totalamt'].fillna(df['totalamt'].mean())

In [53]:
#fill missing values in boardapprovaldate, board_approval_month, closingdate
df['boardapprovaldate'] = df['boardapprovaldate'].fillna(df['boardapprovaldate'].mode()[0])
df['board_approval_month'] = df['board_approval_month'].fillna(df['board_approval_month'].mode()[0])
df['closingdate'] = df['closingdate'].fillna(df['closingdate'].mode()[0])

,id,regionname,countryname,prodline,lendinginstr,lendinginstrtype,envassesmentcategorycode,supplementprojectflg,productlinetype,projectstatusdisplay,status,project_name,boardapprovaldate,board_approval_month,closingdate,lendprojectcost,ibrdcommamt,idacommamt,totalamt,grantamt,borrower,impagency,url
0,P162228,Other,World,RE,Investment Project Financing,IN,C,N,L,Active,Active,Creating a Trade in Value-Added Database for ...,2018-06-28 00:00:00+00:00,June,NaT,500000.00,0.00,0.00,0.00,500000.00,EET,IIST,http://projects.worldbank.org/P162228?lang=en
1,P163962,Africa,Democratic Republic of the Congo,PE,Investment Project Financing,IN,B,N,L,Active,Active,Productive Inclusion Project,2018-06-28 00:00:00+00:00,June,2023-12-31 00:00:00+00:00,200000000.00,0.00,200000000.00,200000000.00,0.00,EET,IIST,http://projects.worldbank.org/P163962?lang=en
2,P167672,South Asia,People's Republic of Bangladesh,PE,Investment Project Financing,IN,B,Y,L,Active,Active,Additional Financing for Health Sector Support...,2018-06-28 00:00:00+00:00,June,NaT,50000000.00,0.00,58330000.00,58330000.00,0.00,EET,IIST,http://projects.worldbank.org/P167672?lang=en
3,P158768,South Asia,Islamic Republic of Afghanistan,PE,Investment Project Financing,IN,A,N,L,Active,Active,Public-Private Partnerships and Public Investm...,2018-06-27 00:00:00+00:00,June,2023-06-28 00:00:00+00:00,50000000.00,0.00,20000000.00,20000000.00,0.00,IIST,IIST,http://projects.worldbank.org/P158768?lang=en
4,P161364,Africa,Federal Republic of Nigeria,PE,Investment Project Financing,IN,B,N,L,Active,Active,Nigeria For Women Project,2018-06-27 00:00:00+00:00,June,2023-05-31 00:00:00+00:00,100000000.00,0.00,100000000.00,100000000.00,0.00,EET,IIST,http://projects.worldbank.org/P161364?lang=en

In [56]:
#fill missing values in datetime columns
df['boardapprovaldate'] = df['boardapprovaldate'].fillna(df['boardapprovaldate'].mode()[0])
df['closingdate'] = df['closingdate'].fillna(df['closingdate'].mode()[0])
df['board_approval_month'] = df['board_approval_month'].fillna(df['board_approval_month'].mode()[0])